"""init_clean

Revision ID: 2fb1a20bf3d5
Revises: 
Create Date: 2026-03-03 12:52:09.376099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2fb1a20bf3d5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('direction', sa.Enum('IN', 'OUT', name='direction_enum'), nullable=False),
    sa.Column('status', sa.Enum('settled', 'pending', 'failed', name='status_enum'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_id')
    )
    op.drop_table('idempotency_keys')
    op.drop_index(op.f('idx_accounts_user_id_'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_table('audit_logs')
    op.drop_index(op.f('idx_ledgerentries_account_status'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_table('transaction')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    sa.UniqueConstraint('email', name=op.f('users_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('transaction',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reference_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('withdrawal', 'transfer', 'deposit', name='transaction_type'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('settled', 'failed', 'pending', name='transaction_status'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('from_account_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('to_account_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fee', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['from_account_id'], ['accounts.id'], name=op.f('transaction_from_account_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_account_id'], ['accounts.id'], name=op.f('transaction_to_account_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('transaction_pkey'))
    )
    op.create_table('ledger_entries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('reference_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('direction', postgresql.ENUM('credit', 'debit', name='ledger_direction'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('ledger_entries_account_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('ledger_entries_pkey'))
    )
    op.create_index(op.f('idx_ledgerentries_account_status'), 'ledger_entries', ['account_id', 'direction'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('entity_type', postgresql.ENUM('transaction', 'ledger', 'account', 'user', name='entity_type'), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action', postgresql.ENUM('created', 'failed', 'settled', 'expired', name='action'), autoincrement=False, nullable=False),
    sa.Column('actor_type', postgresql.ENUM('user', 'system', name='actor_type'), autoincrement=False, nullable=False),
    sa.Column('actor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('audit_logs_actor_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_logs_pkey'))
    )
    op.create_table('accounts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('account_type', postgresql.ENUM('user', 'system', 'escrow', 'external', name='account_type'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('name', postgresql.ENUM('platform_cash', 'platform_revenue', name='system_account_name'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('accounts_user_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('accounts_pkey'))
    )
    op.create_index(op.f('idx_accounts_user_id_'), 'accounts', ['user_id'], unique=False)
    op.create_table('idempotency_keys',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('idempotency_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('reference_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('idempotency_keys_pkey')),
    sa.UniqueConstraint('idempotency_key', name=op.f('idempotency_keys_idempotency_key_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('bank_transfers')
    # ### end Alembic commands ###
