"""init

Revision ID: 6bbe76fafd28
Revises: 75a765a6b954
Create Date: 2026-02-28 17:01:29.882401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bbe76fafd28'
down_revision: Union[str, Sequence[str], None] = '75a765a6b954'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bank_transfers', 'reference_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bank_transfers', 'reference_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
