"""fix

Revision ID: b371ff20e11d
Revises: 6bbe76fafd28
Create Date: 2026-02-28 17:07:42.033206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b371ff20e11d'
down_revision: Union[str, Sequence[str], None] = '6bbe76fafd28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('direction', sa.Enum('IN', 'OUT', name='direction_enum'), nullable=False),
    sa.Column('status', sa.Enum('success', 'pending', 'failed', name='status_enum'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bank_transfers')
    # ### end Alembic commands ###
