"""unique constraint in ledgerentry

Revision ID: 5c64e0d3656b
Revises: 14990513c12c
Create Date: 2026-03-01 20:56:01.774406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c64e0d3656b'
down_revision: Union[str, Sequence[str], None] = '14990513c12c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_ledger_reference_direction', 'ledger_entries', ['reference_id', 'direction'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_ledger_reference_direction', 'ledger_entries', type_='unique')
    # ### end Alembic commands ###
