"""changes in transaction table

Revision ID: 5fb0559d3655
Revises: f6b4424684ad
Create Date: 2026-03-02 12:05:40.683491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fb0559d3655'
down_revision: Union[str, Sequence[str], None] = 'f6b4424684ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('fee', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'fee')
    # ### end Alembic commands ###
