"""index in ledgerentry

Revision ID: d5ee57a94106
Revises: 5c64e0d3656b
Create Date: 2026-03-01 22:26:32.539295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5ee57a94106'
down_revision: Union[str, Sequence[str], None] = '5c64e0d3656b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_ledger_reference_direction'), 'ledger_entries', type_='unique')
    op.create_index('idx_ledgerentries_account_status', 'ledger_entries', ['account_id', 'direction'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ledgerentries_account_status', table_name='ledger_entries')
    op.create_unique_constraint(op.f('uq_ledger_reference_direction'), 'ledger_entries', ['reference_id', 'direction'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
