"""create column name in account

Revision ID: d6037b7e60c0
Revises: 58d1244a685a
Create Date: 2026-03-02 16:33:17.471832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6037b7e60c0'
down_revision: Union[str, Sequence[str], None] = '58d1244a685a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('platform_cash', 'platform_revenue', name='system_account_name').create(op.get_bind())
    op.add_column('accounts', sa.Column('name', sa.Enum('platform_cash', 'platform_revenue', name='system_account_name'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'name')
    sa.Enum(name='system_account_name').drop(op.get_bind())
    # ### end Alembic commands ###
