"""changes in transaction table

Revision ID: f6b4424684ad
Revises: 81c5489e7c0c
Create Date: 2026-03-02 11:39:33.283529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6b4424684ad'
down_revision: Union[str, Sequence[str], None] = '81c5489e7c0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('from_account_id', sa.Integer(), nullable=True))
    op.add_column('transaction', sa.Column('to_account_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('transaction_account_id_fkey'), 'transaction', type_='foreignkey')
    op.create_foreign_key(None, 'transaction', 'accounts', ['to_account_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'transaction', 'accounts', ['from_account_id'], ['id'], ondelete='SET NULL')
    op.drop_column('transaction', 'account_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.create_foreign_key(op.f('transaction_account_id_fkey'), 'transaction', 'accounts', ['account_id'], ['id'], ondelete='SET NULL')
    op.drop_column('transaction', 'to_account_id')
    op.drop_column('transaction', 'from_account_id')
    # ### end Alembic commands ###
